// MFCG GeoJSON export format (v0.11+)
// Generated by https://watabou.github.io/city-generator/

export type Pt2 = [number, number]

// ─── Feature types ────────────────────────────────────────────────────────────

export interface MFCGValues {
  type:          'Feature'
  id:            'values'
  roadWidth:     number
  towerRadius:   number
  wallThickness: number
  generator:     string
  version:       string
  riverWidth?:   number
}

export interface MFCGMultiPolygon {
  type:        'MultiPolygon'
  id:          string
  coordinates: Pt2[][][]  // [polygon[ring[pt]]]
}

export interface MFCGPolygonGeom {
  type:        'Polygon'
  coordinates: Pt2[][]
  name?:       string
}

export interface MFCGLineString {
  type:        'LineString'
  coordinates: Pt2[]
  name?:       string
}

export type MFCGGeometry = MFCGPolygonGeom | MFCGLineString

export interface MFCGGeometryCollection {
  type:       'GeometryCollection'
  id:         string
  geometries: MFCGGeometry[]
}

export interface MFCGMultiPoint {
  type:        'MultiPoint'
  id:          string
  coordinates: Pt2[]
}

export type MFCGFeature =
  | MFCGValues
  | MFCGMultiPolygon
  | MFCGGeometryCollection
  | MFCGMultiPoint
  | { type: 'Polygon'; id: string; coordinates: Pt2[][] }

export interface MFCGJson {
  type:     'FeatureCollection'
  features: MFCGFeature[]
}

// Alias used throughout the codebase
export type CityJSON = MFCGJson

// ─── Helpers ─────────────────────────────────────────────────────────────────

export function getFeature<T extends MFCGFeature>(json: MFCGJson, id: string): T | undefined {
  return json.features.find(f => f.id === id) as T | undefined
}

export function isMFCGJson(obj: unknown): obj is MFCGJson {
  if (!obj || typeof obj !== 'object') return false
  const j = obj as Record<string, unknown>
  if (j['type'] !== 'FeatureCollection') return false
  if (!Array.isArray(j['features'])) return false
  return (j['features'] as MFCGFeature[]).some(f => f.id === 'buildings')
}

